### ISSUE TITLE
TypeError: only valid absolute URLs can be requested

### ISSUE THREAD

**Issue by yashjikhannaji** [lowdefy/lowdefy-example-openid-connect#1]
Error: Error: Issuer.discover() failed.
    TypeError: only valid absolute URLs can be requested
    TypeError: only valid absolute URLs can be requested
    at Object.login (https://blocks-cdn.lowdefy.com/v3.14.1/renderer/70.js:55:328)

**Comment by yashjikhannaji** [comment]
I followed the readme steps but I'm getting this while server startup. 

Error: Error: Issuer.discover() failed.
    TypeError: only valid absolute URLs can be requested
    TypeError: only valid absolute URLs can be requested
    at Object.login (https://blocks-cdn.lowdefy.com/v3.14.1/renderer/70.js:55:328)

**Comment by SamTolmay** [comment]
Hi @yashjikhannaji 
Have you included the "https://" prefix as part of your OpenID Connect domain?

**Comment by SamTolmay** [comment]
The OpenID Connect URL should contain the `https://` URL protocol prefix. This has been updated in the readme.

**Comment by yashjikhannaji** [comment]
Thankyou
